"""Integration tests for AnalyzerAgent using real Confident AI thread data.

These tests use actual thread IDs that were generated by running real
endpoint calls. They test the full fetch → analyze flow with real data.

To regenerate the thread data, run:
    python scripts/generate_thread_traces.py

Requirements for these tests:
    - CONFIDENT_API_KEY must be set in environment
    - The thread IDs in real_thread_ids.json must exist in Confident AI
"""

import json
import os
import unittest
from pathlib import Path

import requests

# Load real thread IDs
THREAD_IDS_FILE = Path(__file__).parent / "real_thread_ids.json"

REAL_THREAD_IDS = {}
if THREAD_IDS_FILE.exists():
    with open(THREAD_IDS_FILE) as f:
        REAL_THREAD_IDS = json.load(f)

HAS_REAL_THREADS = bool(REAL_THREAD_IDS)
HAS_API_KEY = bool(os.environ.get("CONFIDENT_API_KEY"))

# A dummy OpenAI key lets the module-level ChatOpenAI in utils.model import cleanly
# so this file can be COLLECTED and then skipped via skipUnless below. The real gate
# for actually running these tests is CONFIDENT_API_KEY (HAS_API_KEY). Mirrors the
# same setdefault in test_analyzer_agent.py.
os.environ.setdefault("OPENAI_API_KEY", "test-key")

from agents.analyzer_agent import (
    ANALYZER_PATH,
    AnalysisResult,
    AnalyzerAgent,
)


def load_thread_id(key: str) -> str | None:
    """Load a thread ID from the saved config."""
    return REAL_THREAD_IDS.get(key, {}).get("thread_id")


@unittest.skipUnless(
    HAS_REAL_THREADS and HAS_API_KEY,
    "Real thread IDs or CONFIDENT_API_KEY not available"
)
class TestAnalyzerWithRealThreadData(unittest.TestCase):
    """Test analyzer agent with real traces from Confident AI."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.agent = AnalyzerAgent()
        cls.thread_1_id = load_thread_id("thread_1_status_report")
        cls.thread_2_id = load_thread_id("thread_2_schedule_meeting")

        # Probe once: if the configured threads don't exist in this Confident AI
        # account (HTTP 404), the saved real_thread_ids.json is STALE — that's a test
        # fixture/data problem, not a code failure, so skip the whole class with a
        # clear message instead of failing + burning live API calls. A non-404 error
        # (e.g. 401 bad key) is a real problem and is allowed to surface.
        if cls.thread_1_id:
            try:
                cls.agent.fetch_traces_by_thread(cls.thread_1_id)
            except requests.exceptions.HTTPError as exc:
                status = getattr(exc.response, "status_code", None)
                if status == 404:
                    raise unittest.SkipTest(
                        "Configured thread IDs not found in Confident AI (404); "
                        "tests/real_thread_ids.json is stale. Regenerate it by running "
                        "the provider pipeline with a thread_id and saving the new ids."
                    )
                raise

    def test_fetch_traces_thread_1_status_report(self) -> None:
        """Test fetching traces from real thread 1 (status report flow)."""
        if not self.thread_1_id:
            self.skipTest("Thread 1 ID not available")

        traces = self.agent.fetch_traces_by_thread(self.thread_1_id)

        # Should have traces for identify_task, search_workflows, create_workflow, edit_workflow
        self.assertGreaterEqual(len(traces), 3, "Expected at least 3 traces in thread 1")

        # Check trace structure
        for trace in traces:
            self.assertIsInstance(trace.trace_id, str)
            self.assertIsInstance(trace.input, str)
            self.assertIsInstance(trace.output, str)
            self.assertIsInstance(trace.metadata, dict)
            self.assertIsInstance(trace.spans, list)

        print(f"\n   Thread 1 has {len(traces)} traces")
        for i, t in enumerate(traces):
            print(f"     Trace {i+1}: {t.metadata.get('name', 'unnamed')[:50]}...")

    def test_fetch_traces_thread_2_schedule_meeting(self) -> None:
        """Test fetching traces from real thread 2 (schedule meeting flow)."""
        if not self.thread_2_id:
            self.skipTest("Thread 2 ID not available")

        traces = self.agent.fetch_traces_by_thread(self.thread_2_id)

        # Should have traces for identify_task, search_workflows, create_workflow, edit_task
        self.assertGreaterEqual(len(traces), 3, "Expected at least 3 traces in thread 2")

        print(f"\n   Thread 2 has {len(traces)} traces")
        for i, t in enumerate(traces):
            print(f"     Trace {i+1}: {t.metadata.get('name', 'unnamed')[:50]}...")

    def test_analyze_thread_1_full_flow(self) -> None:
        """Test analyzing real thread 1 data end-to-end."""
        if not self.thread_1_id:
            self.skipTest("Thread 1 ID not available")

        result = self.agent.analyze_traces(self.thread_1_id)

        # Should succeed and find insights
        self.assertIn(result.status, ["success", "no_insights"])
        self.assertIsInstance(result.summary, str)
        self.assertGreater(len(result.summary), 0)

        print(f"\n   Thread 1 analysis: {result.summary}")
        if result.user_preferences_added:
            print(f"   User prefs: {len(result.user_preferences_added)} added")
        if result.task_patterns_added:
            print(f"   Task patterns: {len(result.task_patterns_added)} added")
        if result.workflow_trends_added:
            print(f"   Workflow trends: {len(result.workflow_trends_added)} added")

    def test_analyze_thread_2_full_flow(self) -> None:
        """Test analyzing real thread 2 data end-to-end."""
        if not self.thread_2_id:
            self.skipTest("Thread 2 ID not available")

        result = self.agent.analyze_traces(self.thread_2_id)

        self.assertIn(result.status, ["success", "no_insights"])
        self.assertIsInstance(result.summary, str)

        print(f"\n   Thread 2 analysis: {result.summary}")

    def test_analyze_both_threads_comparative(self) -> None:
        """Comparative test: analyze both threads and compare insights."""
        if not self.thread_1_id or not self.thread_2_id:
            self.skipTest("Both thread IDs required")

        result_1 = self.agent.analyze_traces(self.thread_1_id)
        result_2 = self.agent.analyze_traces(self.thread_2_id)

        # Both should complete without errors
        self.assertNotEqual(result_1.status, "error")
        self.assertNotEqual(result_2.status, "error")

        # Thread 1 had an edit_workflow, Thread 2 had an edit_task
        # The analysis should reflect different patterns
        print(f"\n   Thread 1: {result_1.summary}")
        print(f"   Thread 2: {result_2.summary}")


@unittest.skipUnless(HAS_REAL_THREADS, "Real thread IDs not available")
class TestRealThreadIdConfig(unittest.TestCase):
    """Test that thread ID config file is valid."""

    def test_thread_ids_file_exists(self) -> None:
        """Verify the thread IDs file exists and is valid JSON."""
        self.assertTrue(THREAD_IDS_FILE.exists())

        with open(THREAD_IDS_FILE) as f:
            data = json.load(f)

        self.assertIn("thread_1_status_report", data)
        self.assertIn("thread_2_schedule_meeting", data)

    def test_thread_config_structure(self) -> None:
        """Verify each thread config has required fields."""
        with open(THREAD_IDS_FILE) as f:
            data = json.load(f)

        for key, config in data.items():
            self.assertIn("thread_id", config)
            self.assertIn("scenario", config)
            self.assertIn("endpoints_called", config)
            self.assertIsInstance(config["endpoints_called"], list)


if __name__ == "__main__":
    unittest.main(verbosity=2)
